architecture-beta
    service internet(aws:res-internet-alt1-light)[Internet]

    group region(aws:region)[AWS Region]

        group vpc(aws:virtual-private-cloud-vpc)[CAL 001 VPC] in region
            service igw(aws:res-amazon-vpc-internet-gateway)[Internet Gateway] in vpc

            group public_subnet(aws:public-subnet)[Public Subnet] in vpc
                service public_route_table[Public Route Table] in public_subnet

            group private_subnet(aws:private-subnet)[Private Subnet] in vpc
                service private_route_table[Private Route Table] in private_subnet

            service public_security_group[Public Web Security Group] in vpc
            service private_security_group[Private Application Security Group] in vpc

    internet:L <--> R:igw
    igw:B --> T:public_route_table
    public_security_group:R --> L:private_security_group